server:
  port: 9999

spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

redis:
  database: 1
  remote: true
  password:
  timeout: 1000
  maxRedirects: 3
  nodes:
    - 127.0.0.1:7001
    - 127.0.0.1:7002
    - 127.0.0.1:7003
  maxActive: 100 #最大连接数  （使用负值表示没有限制）
  maxIdle: 100 #最大空闲连接数  （使用负值表示没有限制）
  minIdle: 50 #最小空闲连接数
  maxWait: 6000  #获取连接最大等待时间 ms  #default -1


zuul:
  ribbon:
    eager-load:
      enabled: true
#      clients: itfdms-auth,itfdms-upms-service,itfdms-daemon-service
      clients: itfdms-auth
  ignoredServices: '*'
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  ratelimit:
    key-prefix: itfdms-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true
    policies:
      itfdms-upms-service:
        limit: 100
        quota: 100
        refresh-interval: 3

security:
  encode:
    key: '1234567887654321' #必须16位
  validate:
    code: false
  sessions: stateless
  oauth2:
    client:
      client-id: itfdms
      client-secret: itfdms
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check-token
      service-id: itfdms-gateway
      jwt:
        key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

ignore:
  urls:
    - /mobile/**
    - /auth/**
    - /admin/code/*
    - /admin/smsCode/*
    - /admin/user/info
    - /admin/menu/userMenu
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**
  clients:
    - app