server:
  port: 5003

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456.
    url: jdbcUrl: jdbc:mysql//127.0.0.1:3306/itfdms_blog?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true

zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      password: 123456.
      username: admin
      queue: zipkin
  storage:
    type: mysql
